-- Gofun 票务 V1 数据库基线。
-- 该文件冻结主办方、活动、场次、票档、订单和限时开售的最小运行结构。

CREATE TABLE IF NOT EXISTS `dormitory` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `update_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  `building_name` varchar(64) NOT NULL,
  `room_number` varchar(32) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_dormitory_delete_time` (`delete_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- statement
CREATE TABLE IF NOT EXISTS `user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `update_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  `username` varchar(191) NOT NULL,
  `password` longtext NOT NULL,
  `balance` decimal(10,2) DEFAULT NULL,
  `balance_cents` bigint NOT NULL DEFAULT 100000,
  `phone` varchar(20) DEFAULT NULL,
  `avatar_url` varchar(512) DEFAULT NULL,
  `dorm_id` bigint DEFAULT NULL,
  `role` varchar(16) DEFAULT 'user',
  `last_login_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uni_user_username` (`username`),
  KEY `idx_user_delete_time` (`delete_time`),
  KEY `fk_user_dorm` (`dorm_id`),
  CONSTRAINT `fk_user_dorm` FOREIGN KEY (`dorm_id`) REFERENCES `dormitory` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- statement
CREATE TABLE IF NOT EXISTS `organizer` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `update_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `slug` varchar(64) NOT NULL,
  `logo_url` varchar(512) DEFAULT NULL,
  `description` text,
  `contact_name` varchar(64) DEFAULT NULL,
  `contact_phone` varchar(32) DEFAULT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'active',
  `audit_status` varchar(16) NOT NULL DEFAULT 'pending',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_organizer_slug` (`slug`),
  KEY `idx_organizer_delete_time` (`delete_time`),
  KEY `idx_organizer_status` (`status`),
  KEY `idx_organizer_audit_status` (`audit_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- statement
CREATE TABLE IF NOT EXISTS `organizer_member` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `update_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  `organizer_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `role` varchar(16) NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'active',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_organizer_user` (`organizer_id`,`user_id`),
  KEY `idx_organizer_member_delete_time` (`delete_time`),
  KEY `idx_organizer_member_organizer_id` (`organizer_id`),
  KEY `idx_organizer_member_user_id` (`user_id`),
  KEY `idx_organizer_member_status` (`status`),
  CONSTRAINT `fk_organizer_member_organizer` FOREIGN KEY (`organizer_id`) REFERENCES `organizer` (`id`),
  CONSTRAINT `fk_organizer_member_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- statement
CREATE TABLE IF NOT EXISTS `venue` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `update_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  `organizer_id` bigint NOT NULL,
  `name` varchar(128) NOT NULL,
  `city` varchar(64) NOT NULL,
  `district` varchar(64) DEFAULT NULL,
  `address` varchar(256) NOT NULL,
  `latitude` decimal(10,7) DEFAULT NULL,
  `longitude` decimal(10,7) DEFAULT NULL,
  `timezone` varchar(64) NOT NULL DEFAULT 'Asia/Shanghai',
  `status` varchar(16) NOT NULL DEFAULT 'active',
  PRIMARY KEY (`id`),
  KEY `idx_venue_delete_time` (`delete_time`),
  KEY `idx_venue_organizer_id` (`organizer_id`),
  KEY `idx_venue_name` (`name`),
  KEY `idx_venue_city` (`city`),
  KEY `idx_venue_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- statement
CREATE TABLE IF NOT EXISTS `event` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `update_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  `organizer_id` bigint NOT NULL,
  `title` varchar(160) NOT NULL,
  `subtitle` varchar(256) DEFAULT NULL,
  `category` varchar(64) NOT NULL,
  `cover_url` varchar(512) DEFAULT NULL,
  `description` text,
  `status` varchar(24) NOT NULL DEFAULT 'draft',
  `real_name_required` tinyint(1) NOT NULL DEFAULT 0,
  `max_tickets_per_order` bigint NOT NULL DEFAULT 6,
  `published_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_event_delete_time` (`delete_time`),
  KEY `idx_event_organizer_id` (`organizer_id`),
  KEY `idx_event_title` (`title`),
  KEY `idx_event_category` (`category`),
  KEY `idx_event_status` (`status`),
  KEY `idx_event_published_at` (`published_at`),
  CONSTRAINT `fk_event_organizer` FOREIGN KEY (`organizer_id`) REFERENCES `organizer` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- statement
CREATE TABLE IF NOT EXISTS `event_session` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `update_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  `event_id` bigint NOT NULL,
  `venue_id` bigint NOT NULL,
  `starts_at` datetime(3) NOT NULL,
  `ends_at` datetime(3) NOT NULL,
  `sale_starts_at` datetime(3) NOT NULL,
  `sale_ends_at` datetime(3) NOT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'draft',
  `version` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_event_session_delete_time` (`delete_time`),
  KEY `idx_event_session_event_id` (`event_id`),
  KEY `idx_event_session_venue_id` (`venue_id`),
  KEY `idx_event_session_starts_at` (`starts_at`),
  KEY `idx_event_session_sale_starts_at` (`sale_starts_at`),
  KEY `idx_event_session_sale_ends_at` (`sale_ends_at`),
  KEY `idx_event_session_status` (`status`),
  CONSTRAINT `fk_event_session_venue` FOREIGN KEY (`venue_id`) REFERENCES `venue` (`id`),
  CONSTRAINT `fk_event_sessions` FOREIGN KEY (`event_id`) REFERENCES `event` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- statement
CREATE TABLE IF NOT EXISTS `ticket_tier` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `update_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  `session_id` bigint NOT NULL,
  `name` varchar(64) NOT NULL,
  `description` varchar(256) DEFAULT NULL,
  `price_cents` bigint NOT NULL,
  `original_price_cents` bigint DEFAULT NULL,
  `total_quota` bigint NOT NULL,
  `remaining_quota` bigint NOT NULL,
  `sold_count` bigint NOT NULL DEFAULT 0,
  `purchase_limit` bigint NOT NULL DEFAULT 6,
  `status` varchar(16) NOT NULL DEFAULT 'disabled',
  `version` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_ticket_tier_delete_time` (`delete_time`),
  KEY `idx_ticket_tier_session_id` (`session_id`),
  KEY `idx_ticket_tier_remaining_quota` (`remaining_quota`),
  KEY `idx_ticket_tier_status` (`status`),
  CONSTRAINT `fk_event_session_ticket_tiers` FOREIGN KEY (`session_id`) REFERENCES `event_session` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- statement
CREATE TABLE IF NOT EXISTS `ticket_order` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `update_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  `order_no` varchar(32) NOT NULL,
  `user_id` bigint NOT NULL,
  `organizer_id` bigint NOT NULL,
  `event_id` bigint NOT NULL,
  `session_id` bigint NOT NULL,
  `rush_sale_campaign_id` bigint DEFAULT NULL,
  `order_source` varchar(16) NOT NULL,
  `status` varchar(24) NOT NULL,
  `payment_status` varchar(16) NOT NULL,
  `total_amount_cents` bigint NOT NULL,
  `idempotency_key` varchar(64) DEFAULT NULL,
  `request_id` varchar(64) DEFAULT NULL,
  `expires_at` datetime(3) NOT NULL,
  `paid_at` datetime(3) DEFAULT NULL,
  `cancelled_at` datetime(3) DEFAULT NULL,
  `cancel_reason` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_ticket_order_order_no` (`order_no`),
  UNIQUE KEY `uk_ticket_order_idempotency` (`user_id`,`idempotency_key`),
  KEY `idx_ticket_order_delete_time` (`delete_time`),
  KEY `idx_ticket_order_user_id` (`user_id`),
  KEY `idx_ticket_order_organizer_id` (`organizer_id`),
  KEY `idx_ticket_order_event_id` (`event_id`),
  KEY `idx_ticket_order_session_id` (`session_id`),
  KEY `idx_ticket_order_rush_sale_campaign_id` (`rush_sale_campaign_id`),
  KEY `idx_ticket_order_order_source` (`order_source`),
  KEY `idx_ticket_order_status` (`status`),
  KEY `idx_ticket_order_payment_status` (`payment_status`),
  KEY `idx_ticket_order_request_id` (`request_id`),
  KEY `idx_ticket_order_expires_at` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- statement
CREATE TABLE IF NOT EXISTS `ticket_order_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `update_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  `order_id` bigint NOT NULL,
  `ticket_tier_id` bigint NOT NULL,
  `quantity` bigint NOT NULL,
  `unit_price_cents` bigint NOT NULL,
  `event_title_snapshot` varchar(160) NOT NULL,
  `session_starts_at_snapshot` datetime(3) NOT NULL,
  `venue_name_snapshot` varchar(128) NOT NULL,
  `venue_address_snapshot` varchar(256) NOT NULL,
  `tier_name_snapshot` varchar(64) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ticket_order_item_delete_time` (`delete_time`),
  KEY `idx_ticket_order_item_order_id` (`order_id`),
  KEY `idx_ticket_order_item_ticket_tier_id` (`ticket_tier_id`),
  CONSTRAINT `fk_ticket_order_items` FOREIGN KEY (`order_id`) REFERENCES `ticket_order` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- statement
CREATE TABLE IF NOT EXISTS `rush_sale_campaign` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `update_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  `organizer_id` bigint NOT NULL,
  `ticket_tier_id` bigint NOT NULL,
  `name` varchar(128) NOT NULL,
  `rush_price_cents` bigint NOT NULL,
  `total_quota` bigint NOT NULL,
  `remaining_quota` bigint NOT NULL,
  `per_user_limit` bigint NOT NULL DEFAULT 1,
  `starts_at` datetime(3) NOT NULL,
  `ends_at` datetime(3) NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'draft',
  PRIMARY KEY (`id`),
  KEY `idx_rush_sale_campaign_delete_time` (`delete_time`),
  KEY `idx_rush_sale_campaign_organizer_id` (`organizer_id`),
  KEY `idx_rush_sale_campaign_ticket_tier_id` (`ticket_tier_id`),
  KEY `idx_rush_sale_campaign_starts_at` (`starts_at`),
  KEY `idx_rush_sale_campaign_ends_at` (`ends_at`),
  KEY `idx_rush_sale_campaign_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
