-- 一张购买数量对应一张入场票；核销尝试独立留痕。

CREATE TABLE IF NOT EXISTS `admission_ticket` (
  `id` bigint NOT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  `ticket_no` varchar(32) NOT NULL,
  `order_id` bigint NOT NULL,
  `order_item_id` bigint NOT NULL,
  `sequence_no` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `organizer_id` bigint NOT NULL,
  `event_id` bigint NOT NULL,
  `session_id` bigint NOT NULL,
  `ticket_tier_id` bigint NOT NULL,
  `status` varchar(16) NOT NULL,
  `issued_at` datetime(3) NOT NULL,
  `used_at` datetime(3) DEFAULT NULL,
  `revoked_at` datetime(3) DEFAULT NULL,
  `revoke_reason` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_admission_ticket_ticket_no` (`ticket_no`),
  UNIQUE KEY `uk_ticket_unit` (`order_item_id`,`sequence_no`),
  KEY `idx_admission_ticket_delete_time` (`delete_time`),
  KEY `idx_admission_ticket_order_id` (`order_id`),
  KEY `idx_admission_ticket_order_item_id` (`order_item_id`),
  KEY `idx_admission_ticket_user_id` (`user_id`),
  KEY `idx_admission_ticket_organizer_id` (`organizer_id`),
  KEY `idx_admission_ticket_event_id` (`event_id`),
  KEY `idx_admission_ticket_session_id` (`session_id`),
  KEY `idx_admission_ticket_ticket_tier_id` (`ticket_tier_id`),
  KEY `idx_admission_ticket_status` (`status`),
  KEY `idx_admission_ticket_issued_at` (`issued_at`),
  CONSTRAINT `fk_admission_ticket_order` FOREIGN KEY (`order_id`) REFERENCES `ticket_order` (`id`),
  CONSTRAINT `fk_admission_ticket_order_item` FOREIGN KEY (`order_item_id`) REFERENCES `ticket_order_item` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- statement
CREATE TABLE IF NOT EXISTS `ticket_verification_record` (
  `id` bigint NOT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  `ticket_id` bigint DEFAULT NULL,
  `success_ticket_id` bigint DEFAULT NULL,
  `organizer_id` bigint NOT NULL,
  `operator_user_id` bigint NOT NULL,
  `credential_fingerprint` varchar(64) NOT NULL,
  `result` varchar(32) NOT NULL,
  `detail` varchar(256) DEFAULT NULL,
  `verified_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_ticket_verification_record_success_ticket_id` (`success_ticket_id`),
  KEY `idx_ticket_verification_record_delete_time` (`delete_time`),
  KEY `idx_ticket_verification_record_ticket_id` (`ticket_id`),
  KEY `idx_ticket_verification_record_organizer_id` (`organizer_id`),
  KEY `idx_ticket_verification_record_operator_user_id` (`operator_user_id`),
  KEY `idx_ticket_verification_record_credential_fingerprint` (`credential_fingerprint`),
  KEY `idx_ticket_verification_record_result` (`result`),
  KEY `idx_ticket_verification_record_verified_at` (`verified_at`),
  CONSTRAINT `fk_verification_ticket` FOREIGN KEY (`ticket_id`) REFERENCES `admission_ticket` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
